Feature/1 blog
Lisyushka/fox pull request #6
Opened 2024-05-20 11:22 UTC by Lisyushka

Обновила знания, доделала код ревью второе. Сделала так как поняла. Далее буду корректировать с флексами и гридами. Надеюсь что накосячила минимально. С нетерпением жду проверки))

2024-05-20 11:36 UTC, GitEsense requested changes
Отправляю на доработку, необходимо обратить внимание на комментарии и немного "перестилизовать"

2024-05-20 11:36 UTC, GitEsense commented on blog.html
> +                </div>
Ну тут в форме div будет лишний, лучше просто оставить один инпут, а для семантики добавить пустой label

2024-05-20 11:36 UTC, GitEsense commented on blog.html
> +                <li><a href="#" class="blog">Мой блог</a></li>
Это так же часть логотипа, т.е. это будет и иконка, и текст "одной ссылкой", поэтому можно вынести в div.logo

2024-05-20 11:36 UTC, GitEsense commented on blog.html
> +            <div class="name"> Наталья Васильева
Раз уж у нас текстовый контент, то хорошо было бы сделать это параграфом - это же касается и "профессии"

2024-05-20 11:36 UTC, GitEsense commented on style-blog/style.css
> +    padding: 71px 180px 69px 0;
нет, такого в форме точно нет, в инпуте padding (это внутренний отступ от контекста \ текста) у нас будет 12px 9px 12px 49px, либо воспользоваться letter-spacing: 49px

2024-05-20 11:36 UTC, GitEsense commented on style-blog/style.css
> +    padding: 0 457px 30px 458px;
Аналогично, мы не позиционируем через такие padding'и, и марджины, если мы хотим поставить блок в центр блока - мы можем использовать margin: 0 auto;

2024-05-20 11:36 UTC, GitEsense commented on style-blog/style.css
> +    height: 76px;
Высоту лучше вообще нигде не ограничивать - это лишнее, пусть контент берёт сколько ему надо, а ширину указываем как max-width: 525px - тут это верно

2024-05-20 11:36 UTC, GitEsense commented on style-blog/style.css
> +    padding: 0 606px 77px 608px;
Ну и как и везде - аналогично - надо избавиться

2024-05-20 11:36 UTC, GitEsense commented on style-blog/style.css
> +}
Вот это всё тоже убираем - это не нужно, мы стилизуем только ссылки, по сути
```css
a, nav a {
    color: #fff;
    font-size: 16px;
    font-weight: 400;
    text-decoration: none;
}
```

2024-05-20 11:36 UTC, GitEsense commented on style-blog/style.css
>  }
то же самое касается и текста - не нужно ограничивать размеры - мы всё остальное доделаем (вывод в одну строку) - уже потом при практике flex-box

2024-05-20 11:36 UTC, GitEsense commented on style-blog/style.css
> +    padding: 0 272px 69px;
padding не нужен
размеры лучше указывать как max-width / max-height, если только нам не нужно "принудительно" дать такой размер и никакой больше

2024-05-20 11:36 UTC, GitEsense commented on blog.html
> +                <li><a href="#" class="backend">Backend</a></li>
это будет лишнее для каждого "li > a" указывать свой класс, можем сделать один класс, например nav__link и его стилизовать, либо через родителя (этот пример уже в CSS ниже приведён), либо глобально

2024-05-21 12:12 UTC, Lisyushka commented on style-blog/style.css
> +}
тоесть мне не нужно их размещать в пространстве, я правильно понимаю? мне нужно убрать все что в этих строках и заменить на те что в твоем комменте? это потом сделается при помощи флексов и гридов? просто задание было разместить вертикально, и я теперь немножко запуталась.

2024-05-23 07:59 UTC, GitEsense requested changes
Необходимо поправить отступы внешние и внутренние (margin / padding) - не нужно позиционировать "в ручную", на всякий случай рекомендую ознакомиться ещё раз с разделом про блочную модель и "отступы"

2024-05-23 07:59 UTC, GitEsense commented on blog.html
> +        </div>
Это можно было бы сделать одной ссылкой
```html
<a href="#"><img src="./img/Vector.png" alt="логотип" /> Мой блог</a>
```
`li` без `ul/ol` не используется, так же ни к чему иметь 2 разные ссылки

2024-05-23 07:59 UTC, GitEsense commented on style-blog/style.css
> +    margin: 0 606px 77px 608px;
И снова - ограничений по высоте вообще по сути в этом макете не должно быть. margin должен быть "оптимальным", т.е. отступ от блока к блоку 100px ? окей, но слева и права по 606 - это не приемлемо, лучше оставить 0 и пусть блоки будут прижаты к левому краю, потом уже будем центровать "динамически" таких значений быть не должно

2024-05-23 07:59 UTC, GitEsense commented on style-blog/style.css
> +    margin: 72px 11px 73px 180px;
Аналогично и тут - с марджинами

2024-06-06 16:24 UTC, merged